name: "lego"
description: "Lego based lets encrypt integration"
version: "0.0.1"
slug: "lego"
arch:
  - aarch64
#  - amd64
map:
  - config:rw
  - ssl:rw
environment:
  SCALEWAY_API_TOKEN: "174e1657-41b4-41b9-96eb-e217f02c7061"